# Generated by Django 3.1.2 on 2020-10-12 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('breads', 'breads'), ('cereals', 'cereals'), ('diary', 'diary'), ('drinks', 'drinks'), ('fish and seafood', 'fish and seafood'), ('fruits and vegetables', 'fruits and vegetables'), ('meat', 'meat'), ('nuts and seeds', 'nuts and seeds'), ('pastas', 'pastas'), ('sweets', 'sweets'), ('others', 'others')], max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
