# Generated by Django 3.1.2 on 2020-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfooddatabase',
            old_name='user_id',
            new_name='user',
        ),
    ]
