# Generated by Django 3.1.2 on 2020-10-12 14:03

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=jsonfield.fields.JSONField(default={'a': 'b'}),
        ),
        migrations.AddField(
            model_name='dish',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
