# Generated by Django 3.1.2 on 2020-10-12 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_site', '0005_auto_20201012_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('day', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='userfooddatabase',
            unique_together={('user', 'name')},
        ),
    ]
