# Generated by Django 3.1.2 on 2020-10-12 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_site', '0006_auto_20201012_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='Dish', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('user', 'name'), ('day', 'time')},
        ),
    ]
