# Generated by Django 3.1.2 on 2020-10-23 14:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0007_auto_20201012_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=jsonfield.fields.JSONField(default={'ingredient1': {'mass': 0, 'name': ''}}),
        ),
        migrations.AlterField(
            model_name='dish',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('day', 'time')},
        ),
    ]
