# Generated by Django 3.1.2 on 2020-10-23 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_site', '0009_auto_20201023_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('day', 'name', 'user'), ('day', 'time', 'name', 'user')},
        ),
    ]
