# Generated by Django 3.1.2 on 2020-10-26 18:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0011_auto_20201026_1853'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfooddatabase',
            constraint=models.CheckConstraint(check=models.Q(carbohydrates__gte=django.db.models.expressions.F('sugars')), name='check it'),
        ),
    ]
