# Generated by Django 3.1.2 on 2020-10-28 10:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0012_auto_20201026_1927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfooddatabase',
            name='check it',
        ),
        migrations.AddConstraint(
            model_name='userfooddatabase',
            constraint=models.CheckConstraint(check=models.Q(carbohydrates__gte=django.db.models.expressions.F('sugars')), name='Mass of sugars cannot be higher than mass of carbohydrates'),
        ),
        migrations.AddConstraint(
            model_name='userfooddatabase',
            constraint=models.CheckConstraint(check=models.Q(proteins__lte=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.Value(100), '-', django.db.models.expressions.F('carbohydrates')), '-', django.db.models.expressions.F('fats'))), name='Sum of proteins, carbohydrates and fat cannot be greater than 0'),
        ),
    ]
