# Generated by Django 3.1.2 on 2020-10-30 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0008_auto_20201030_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_site', '0013_auto_20201028_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_database.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='UserFoodDatabase',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.dish'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_database.products'),
        ),
    ]
