# Generated by Django 3.1.2 on 2020-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0014_auto_20201030_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='product',
            new_name='ingredient',
        ),
    ]
