# Generated by Django 3.1.2 on 2020-11-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0018_auto_20201106_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttouser',
            unique_together=set(),
        ),
    ]
