# Generated by Django 3.1.2 on 2020-11-13 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_site', '0019_auto_20201113_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('day', 'time', 'user'), ('day', 'name', 'user')},
        ),
    ]
