# Generated by Django 3.1.2 on 2020-10-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('A', 'meat'), ('B', 'fish'), ('C', 'diary'), ('D', 'fruits and vegetables'), ('E', 'breads'), ('F', 'cereals'), ('G', 'pastas'), ('H', 'sweets'), ('I', 'drinks'), ('J', 'nuts and seeds'), ('K', 'others')], max_length=100)),
                ('proteins', models.PositiveIntegerField()),
                ('carbohydrates', models.PositiveIntegerField()),
                ('sugars', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
            ],
        ),
    ]
