# Generated by Django 3.1.2 on 2020-10-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddatabase',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='category',
            field=models.CharField(choices=[('A', 'meat'), ('B', 'fish and seafood'), ('C', 'diary'), ('D', 'fruits and vegetables'), ('E', 'breads'), ('F', 'cereals'), ('G', 'pastas'), ('H', 'sweets'), ('I', 'drinks'), ('J', 'nuts and seeds'), ('K', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='sugars',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
