# Generated by Django 3.1.2 on 2020-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0002_auto_20201011_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='category',
            field=models.CharField(choices=[('B', 'breads'), ('C', 'cereals'), ('D', 'diary'), ('DR', 'drinks'), ('FS', 'fish and seafood'), ('FV', 'fruits and vegetables'), ('M', 'meat'), ('NS', 'nuts and seeds'), ('P', 'pastas'), ('S', 'sweets'), ('X', 'others')], max_length=100),
        ),
    ]
