# Generated by Django 3.1.2 on 2020-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0004_auto_20201011_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='sugars',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
