# Generated by Django 3.1.2 on 2020-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0005_auto_20201011_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
    ]
