# Generated by Django 3.1.2 on 2020-10-30 20:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0007_auto_20201023_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('breads', 'breads'), ('cereals', 'cereals'), ('diary', 'diary'), ('drinks', 'drinks'), ('fish and seafood', 'fish and seafood'), ('fruits and vegetables', 'fruits and vegetables'), ('meat', 'meat'), ('mushrooms', 'mushrooms'), ('nuts and seeds', 'nuts and seeds'), ('oils', 'oils'), ('pastas', 'pastas'), ('sweets', 'sweets'), ('others', 'others')], max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodDatabase',
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(check=models.Q(carbohydrates__gte=django.db.models.expressions.F('sugars')), name='Mass of sugars cannot be higher than mass of carbohydrates'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(check=models.Q(proteins__lte=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.Value(100), '-', django.db.models.expressions.F('carbohydrates')), '-', django.db.models.expressions.F('fats'))), name='Sum of proteins, carbohydrates and fat cannot be greater than 0'),
        ),
    ]
