# Generated by Django 3.1.2 on 2020-11-13 14:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('food_database', '0009_auto_20201113_1530'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='products',
            name='Sum of proteins, carbohydrates and fat cannot be greater than 100',
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(check=models.Q(proteins__lte=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.Value(100), '-', django.db.models.expressions.F('carbohydrates')), '-', django.db.models.expressions.F('fats'))), name='Sum of proteins, carbohydrates and fats cannot be greater than 100'),
        ),
    ]
